# Generated by Django 5.0.1 on 2024-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'order_processed'), (3, 'order_delivered'), (4, 'order_rejected')], default=0),
        ),
    ]
